apiVersion: v1
kind: Service
metadata:
  name: trudeau
  labels:
    app: trudeau
spec:
  selector:
    app: trudeau
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80