apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: trudeau-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.i0/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - https-uselesscunt.org
    secretName: uselesscunt-tls
  rules:
  - host: https-uselesscunt.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trudeau
            port: 
              number: 80
